[package]
name = "rust"
version = "0.1.0"
authors = ["Nathan Esau <nathanesau1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.31"
lazy_static = "1.4.0"
